language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install: 
  - git clone https://github.com/daniel-sc/podio-java.git podio-java
  - cd podio-java
  - mvn clean install -Dmaven.test.skip=true
  - cd ../code-gen
